#!/usr/bin/python
import subprocess
import json
import argparse

parser = argparse.ArgumentParser("Version bumper tool")
group = parser.add_mutually_exclusive_group()
group.add_argument("--major", action="store_true",
                   "Major version number bump")
group.add_argument("--minor", action="store_true",
                   "Minor version number bump")
group.add_argument("--build", action="store_true",
                   "Build number bump")

def bump_version(args):
    with open("version.json") as f:
        major, minor, build = json.load(f)
    if args.major:
        major += 1
        minor = 0
        build = 0
    elif args.minor:
        minor += 1
        build = 0
    else:
        build += 1
    with open("version.json", "w") as f:
        json.dump([major, minor, build], f)
    subprocess.check_call(["git", "commit", "version.json",
                           "-m", "Bump version"])
    subprocess.check_call(["git", "tag",
                           "v%s.%s.%s" % (major, minor, build)])
    subprocess.check_call(["git", "push", "--tags"])

if __name__ == "__main__":
    bump_version(parser.parse_args())
