#!/usr/bin/python
import subprocess
import json
import argparse

parser = argparse.ArgumentParser("Version bumper tool")
group = parser.add_mutually_exclusive_group(required=True)
group.add_argument("--major", action="store_true",
                   help="Major version number bump")
group.add_argument("--minor", action="store_true",
                   help="Minor version number bump")
group.add_argument("--build", action="store_true",
                   help="Build number bump")

def bump_version(args):
    tags = subprocess.check_output(["git", "tag", "-l", 
	"v*.*.*", "--sort", "v:refname"]).split("\n")
    if not tags:
        major = 0
        minor = 0
        build = 0
    else:
        ver = tags[-1][1:].split(".")
        major = int(ver[0])
        minor = int(ver[1])
        build = int(ver[2])
    if args.major:
        major += 1
        minor = 0
        build = 0
    elif args.minor:
        minor += 1
        build = 0
    else:
        build += 1
    subprocess.check_call(["git", "tag",
                           "v%s.%s.%s" % (major, minor, build)])
    subprocess.check_call(["git", "push", "--tags"])    

if __name__ == "__main__":
    bump_version(parser.parse_args())
