#!/bin/sh -xe
if [ -d wheelhouse ]
then
    mv wheelhouse wheelhouse.old
fi
pip wheel --wheel-dir wheelhouse -r requirements.txt --no-cache-dir --find-links wheelhouse.old
pip install --no-index --find-links wheelhouse -r requirements.txt
