#!/bin/sh -xe
SOURCE_DATE_EPOCH=`git show -s --format=%ct`
export SOURCE_DATE_EPOCH
flake8 simplepreprocessor
python -m unittest discover -v
python setup.py bdist_wheel
touch -d @$SOURCE_DATE_EPOCH dist/*
